# -*- coding: utf-8 -*-
"""disiplinlerarası.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18XCt5BmWrWkPJqQfOqY4ErPmRQxYTKKj
"""

!pip install --upgrade pip

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/WongKinYiu/yolov7.git
# %cd yolov7
!pip install -U -r requirements.txt

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
!cp /content/drive/MyDrive/dataset.v1i.yolov7pytorch.zip /content/yolov7/data/
# %cd /content/yolov7/data/
!unzip dataset.v1i.yolov7pytorch.zip

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/yolov7

!ls

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/yolov7
!python /content/yolov7/train.py --img-size 320 --batch-size 16 --epochs 50 --data /content/yolov7/data/data.yaml --cfg /content/yolov7/cfg/training/yolov7.yaml --weights /content/yolov7/yolov7.pt

!python detect.py --weights /content/yolov7/runs/train/exp/weights/best.pt --source /content/yolov7/data/test/images --img-size 320 --conf-thres 0.3